--- #YAML:1.0
name:                     Labyrinth-Plugin-Review
version:                  1.00
abstract:                 Reviews plugin for the Labyrinth framework
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                                   5.006
  Labyrinth:                              5.29
  Clone:                                  0
  Time::Local:                            0
recommends:
  Test::CPAN::Meta:                       0
  Test::CPAN::Meta::JSON:                 0
  Test::Pod:                              1.00
  Test::Pod::Coverage:                    0.08
build_requires:
  IO::File:                               0
  Test::More:                             0.70

provides:
  Labyrinth::Plugin::Review:
    file:     lib/Labyrinth/Plugin/Review.pm
    version:  1.00
  Labyrinth::Plugin::Review::Retailers:
    file:     lib/Labyrinth/Plugin/Review/Retailers.pm
    version:  1.00
  Labyrinth::Plugin::Review::Types:
    file:     lib/Labyrinth/Plugin/Review/Types.pm
    version:  1.00

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-Review
  repository: http://github.com/barbie/labyrinth-plugin-review

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
